# -*- coding: utf-8 -*-
"""SNA project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hvnaVyMdcNJlqmuyz7UeNyiDt8EwaGKC
"""

import networkx as nx

# empty graph
G = nx.Graph()

# Add nodes (influencers, creators, brands)
G.add_nodes_from(["A", "B", "C", "D", "E"])

# Add edges (interactions)
G.add_edges_from([
    ("A", "B"),
    ("A", "C"),
    ("B", "D"),
    ("C", "D"),
    ("D", "E")
])

print("Graph created with:", G.number_of_nodes(), "nodes and", G.number_of_edges(), "edges")

import networkx as nx

# Degree Centrality
degree_centrality = nx.degree_centrality(G)
print("Degree Centrality:", degree_centrality)

# Betweenness Centrality
betweenness = nx.betweenness_centrality(G)
print("Betweenness Centrality:", betweenness)

# Closeness Centrality
closeness = nx.closeness_centrality(G)
print("Closeness Centrality:", closeness)

# PageRank
pagerank_scores = nx.pagerank(G)
print("PageRank:", pagerank_scores)

import numpy as np

# Example: classify nodes with unusually high degree as suspicious
degrees = dict(G.degree())
avg_deg = np.mean(list(degrees.values()))
threshold = avg_deg * 2  # Example rule

suspicious_nodes = [n for n, d in degrees.items() if d > threshold]

print("Suspicious accounts (degree anomaly):", suspicious_nodes)

def recommend_collaborators(graph, node, top_k=3):
    neighbors = list(graph.neighbors(node))
    scores = {}

    for n in graph.nodes():
        if n not in neighbors and n != node:
            # Score = number of shared neighbors
            shared = len(set(neighbors) & set(graph.neighbors(n)))
            scores[n] = shared

    ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    return ranked[:top_k]

# Example usage:
print("Recommended collaborators for A:", recommend_collaborators(G, "A"))

import matplotlib.pyplot as plt
import networkx as nx

plt.figure(figsize=(6,6))
nx.draw(G, with_labels=True, node_size=600, font_size=10)
plt.title("Influencer–Creator Network Graph")
plt.show()